name: FOSSA CLI Analysis
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      
      - name: Convert dependencies
        run: |
          python fossa-deps-conversion.py
          
          cat fossa-deps.json
  
      - name: Download FOSSA CLI
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa --version
          
      - name: FOSSA Analyze Output
        run: |
          fossa analyze -o | jq

      - name: FOSSA Analyze 
        run: |
          fossa analyze --exclude-path . --debug
          
      - uses: actions/upload-artifact@v3
        with:
          name: fossa-debug-logs
          path: ./fossa.debug.json.gz
